version: '3.8'

services:
  mysql:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: root   
      MYSQL_DATABASE: streemi  
      MYSQL_USER: user             
      MYSQL_PASSWORD: password     
    ports:
      - "3306:3306"                
    volumes:
      - mysql_data:/var/lib/mysql:rw  


volumes:
  mysql_data:
